### ISSUE TITLE
MinipH driver

### ISSUE THREAD

**Issue by mr-ma** [reef-pi/drivers#50]
Do you think I could possibly use a [`minipH` sensor](https://www.sparkyswidgets.com/product/miniph/) instead of those sensor types that you currently support? 
I must say I'm new to reef-pi. Based on a quick peek on the code, adding a new driver seems pretty straightforward.
The only itch is that they in their [sample](https://github.com/SparkysWidgets/MinipHBFW/blob/master/RaspberryPi%20-%20Python3/pHReader.py) read from smbus instead of I2C. 
```What do you guys think?```

Cheers

**Comment by ranjib** [comment]
What is the benefit of this over the existing driver? This does not have galvanic isolation which will make it susceptible to bad reading due to electrical inference

**Comment by mr-ma** [comment]
Benefits to me are: 
i) minipH is quite cheaper than the one from atlas scientist; and
ii) minipH comes with a BNC Connector and needs not the carrier board.

I have personally played with the minipH sensor a bit. Reads are, so far, ok.
Why not support an alternative budget sensor?

**Comment by ranjib** [comment]
@mr-ma the opensource ph board is not super expensive compared to this (40$). I doubt i;ll get to write this driver as i am not using it, neither i see this becoming very popular (due to the lack of galvanic isolation). Its mostly from our prior experience (with using analog  inputs without galvanic isolation leading to errorprone results, which are rather hard to diagnose in software), presence of a viable alternate (reef-pi opensource ph board), the effort involved in writing a new driver and chances of this being used by a broad set of users that I am deferring this request. If this ph board is opensource and someone else writes the driver I might consider incorporating it. 

Other than the actual effort in writing new driver it is also a constant maintenance cost that deters us from a whole lot of different drivers for the same functionalities. Since we never use all of them, its hard to test and ensure they are in working properly as the software evolves.
