### ISSUE TITLE
Driver add "write /dev/i2c-1: remote I/O error"

### ISSUE THREAD

**Issue by Vadech** [reef-pi/drivers#57]
Hi,

When I try to add the Ph-board driver, i have this error.
write /dev/i2c-1: remote I/O error

Everything seem fine:
![image](https://user-images.githubusercontent.com/6782832/81503392-aadc0980-92e3-11ea-8409-5a8a1aaed7af.png)

![image](https://user-images.githubusercontent.com/6782832/81503399-b0395400-92e3-11ea-8bdd-d4145aa77f7d.png)

Do you have an idea ?

Thank by advance.

**Comment by ranjib** [comment]
HI can you detail what board you are using? along side the reef-pi version and little but of your setup. reef-pi only uses the opensource ph board driver or ezo driver.

**Comment by Vadech** [comment]
Hi,
Thanks for you answer.
My ReefPi version is:
![image](https://user-images.githubusercontent.com/6782832/82929201-9191b900-9f83-11ea-9151-af1f026d857a.png)

I use an ADS1115:
![WhatsApp Image 2020-05-26 at 18 42 18 (1)](https://user-images.githubusercontent.com/6782832/82929284-b1c17800-9f83-11ea-8bcc-e748c4fd544e.jpeg)
![WhatsApp Image 2020-05-26 at 18 42 17](https://user-images.githubusercontent.com/6782832/82929297-b71ec280-9f83-11ea-89a4-2080a6a23f70.jpeg)
![WhatsApp Image 2020-05-26 at 18 42 18](https://user-images.githubusercontent.com/6782832/82929318-c00f9400-9f83-11ea-8ba9-1113d1afefd3.jpeg)

What do you mean with "the opensource ph board driver" ?
How can i check that ?

For information, my "simpletest.py" works ONLY with python3 and not with python.
Maybe it's the problem ??? 
But I dont' kno how to fix it.

Thank you.

**Comment by Vadech** [comment]
The error message:
![image](https://user-images.githubusercontent.com/6782832/82930434-aec78700-9f85-11ea-9530-a86ffdbd58e4.png)

And my setting:
![image](https://user-images.githubusercontent.com/6782832/82930459-bd15a300-9f85-11ea-948a-2f4660e5e3e3.png)

**Comment by Ranthalion** [comment]
The pH board driver is compatible with ADS1119, so it will not work with ADS1115.
We have a separate issue to [add support for ADS1015/ADS1115](https://github.com/reef-pi/reef-pi/issues/1155).  I expect to begin working on that feature in June.

I'm closing this issue since it is not currently supported.

**Comment by Vadech** [comment]
Ok, thank's for your quick answer. Can i help you ? I can try to implement it if you explain me quickly how and where code this. Did you have a developper guide ?
June is perfect if it's longer to explain to me than to developper by yourself ;-).

**Comment by Ranthalion** [comment]
You are welcome to give it a shot.  I was planning to start on it this weekend, after I finish adding a few more light profiles to the UI.  

We have a developer guide at https://reef-pi.github.io/additional-documentation/development/.  It does not address driver development directly, but you would need to be able to build and run reef-pi in order to confirm the driver works.  We also have a slack channel for more realtime dev discussion. 

Developing the driver would require implementing the Driver, DriverFactory, AnalogInputDriver, and AnalogInputPin interfaces.  You could use the [pH-board driver](https://github.com/reef-pi/drivers/tree/master/ph_board) as a sample.
